NON_KEYWORDS=USER
DROP TABLE city IF EXISTS;
CREATE TABLE `city` (
    `name` VARCHAR(250) PRIMARY KEY,
    `department` VARCHAR(250)
);

CREATE TABLE `user` (
    `id` INTEGER PRIMARY KEY ,
    `name` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL
);